### ISSUE TITLE
赋默认值是否可以支持类型推导？

### ISSUE THREAD

**Issue by hzqd** [zjp-CN/structs_new#1]
对结构体的字段做类型推导，这在理论上似乎是可行的。

如：[structx!](https://crates.io/crates/structx) 这个库，实现了匿名结构体字段的类型推导。

**Comment by zjp-CN** [comment]
类型推导不是由库做的，而是编译器做的。

比如 `structx!{ x, y };` 这个匿名结构体中，其字段 x 和 y 的类型在上下文中是完全已知的。
